connectors:
- type: oidc
  id: aad
  name: AzureAD
  config:
    # Canonical URL of the provider, also used for configuration discovery.
    # This value MUST match the value returned in the provider config discovery.
    #
    # See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
    issuer: https://login.microsoftonline.com

    # Connector config values starting with a "$" will read from the environment.
    clientID: d91871e4-fa57-4b5f-92a3-23f158733976
    clientSecret: 3jU/RyVo/pX:u_iWCbSuPXRmrj1cDV55

    # Dex's issuer URL + "/callback"
    redirectURI: https://dex.sso.40.118.226.223.nip.io/callback


    # Some providers require passing client_secret via POST parameters instead
    # of basic auth, despite the OAuth2 RFC discouraging it. Many of these
    # cases are caught internally, but some may need to uncommented the
    # following field.
    #
    # basicAuthUnsupported: true
    
    # Google supports whitelisting allowed domains when using G Suite
    # (Google Apps). The following field can be set to a list of domains
    # that can log in:
    #
    # hostedDomains:
    #  - example.com

    # List of additional scopes to request in token response
    # Default is profile and email
    # Full list at https://github.com/dexidp/dex/blob/master/Documentation/custom-scopes-claims-clients.md
     scopes:
    #  - profile
      - email
    #  - groups